name: Continous integration
on:
  workflow_dispatch:
  pull_request:
    # only PR for master
    branches:
      - master
      - next
      - vNext
jobs:
  continous_integration:
    runs-on: ubuntu-latest  # ← GEÄNDERT: von macOS-latest zu ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4  # ← GEÄNDERT: von v2 zu v4 (aktueller)
      - name: NodeJS setup
        uses: actions/setup-node@v4  # ← GEÄNDERT: von v2 zu v4 (aktueller)
        with:
          node-version: 18  # ← GEÄNDERT: von 14 zu 18 (LTS Version)
          registry-url: https://registry.npmjs.org/
      - name: Installing dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test+coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
